### ISSUE TITLE
HiveSlot +

### ISSUE THREAD

**Issue by AsianRiceFarmer365** [NatroTeam/NatroMacro#14]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

So on the macro, there will be a  more advanced settings for hive slots (similar to the discord interrogation). We can add a preferred hive slot, and the macro will search for it upon joining the game. If the slot is taken, it will reset and check another preferred slot or it will go to the closest slot to red cannon. This feature will be very useful if you like the third slot when macroing in pine etc.

### How will this improve Natro Macro?

Users can have more customisation for their selection of hive slots.

### What is your Discord username?

AsianRiceFarmer365

**Comment by Aaxelpediaa** [comment]
That feature already exists I think, it's under Settings --> Hive Slot (on the left)

**Comment by AsianRiceFarmer365** [comment]
ok

**Comment by zspz** [comment]
@AsianRiceFarmer365 
Just want to clarify since you were given two contradicting answers: all of your suggestion does exist **except** checking for a secondary preferred slot.
- Your preferred hive slot is the 'Hive Slot' chosen in Settings tab, the macro will always claim this one if it isn't taken.
- If the slot is taken, there is no 'secondary preferred slot' mechanism, it will just go for the hive slot closest to red cannon.

If you want the choice to add a secondary preferred hive slot, then let me know and I'll change this issue's title. I personally don't see a need for this and it would unnecessarily complicate the GUI, but if others would like this added it won't be difficult.
Otherwise, I'll close this issue.

**Comment by zspz** [comment]
closed for inactivity
