### ISSUE TITLE
An option to skip smoking planters when collecting planters

### ISSUE THREAD

**Issue by xX-ShinyPr0-Xx** [NatroTeam/NatroMacro#152]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Have an option to toggle between collecting/not collecting smoking planters and include exceptions (e.g. anything lower than tacky). 

### How will this improve Natro Macro?

This will benefit players who want to do puff parties to obtain turpentine/waxes etc.

### What is your Discord username?

impactraider

**Comment by rpertusio** [comment]
Please check release notes of v0.9.8 relating to "Disable Auto Harvest for Manual Planters" where a screenshot can be sent in Discord for you.  Does that fulfill this feature request?

**Comment by misc-et** [comment]
Yes, the disable auto harvest feature (with optional screenshot and ability to set status to smoking/release via remote control) was added in v0.9.8 as an alternative approach. 

This is because the transparency and variability of the planter smoke would make it difficult to detect reliably using the macro.
