### ISSUE TITLE
Auto Nectar Condenser

### ISSUE THREAD

**Issue by PiteroZero** [NatroTeam/NatroMacro#159]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I know this update is really new and you probably had this idea but:
1.You can add auto Nectar Condeser so people that are currently farming for quests/items and not honey can get some vials.
2. Auto Yellow Walking Wiggly Person completion. I did it already but its boring AF and I bet people would use it a lot.
3. New gathering rotation only for stickers. (f.e. in the hub)
4. ! This is really importnat - auto sticker stack boost - either with tickets or with a sticker.
Thats all from me. Cya

### How will this improve Natro Macro?

1.As I said it would make people (like me) farming for items and quests get nectar vials which would be nice to have when I finally get the item I am collecting recourses for.
2.Its just hell ass annoying...
3.Stickers are really important imo
4.It can make boost be about 10 times more productive for a price of idk 24 stickers a day or 600 tickets (its actually isnt that small but I bet they are ppl that can pay that price)

### What is your Discord username?

piterozero

**Comment by zspz** [comment]
Hi,
I'll answer your suggestions one-by-one:
1. While this could be added in the future, I don't see a clear use to get the macro to do this so it may remain low priority for a while.
2. Since this is a one-time achievement, I don't think it should be added to Natro Macro.
3. This may be added in the future. Good suggestion!
4. This has been added and will be released very soon!
I'll change this issue's title so it's more clear what this post is about.

**Comment by zspz** [comment]
For Hive Hub macro ideas, refer to #185.

**Comment by Noobyguy775** [comment]
Use #282 for furter ideas about the nectar condenser.
