### ISSUE TITLE
Roblox new link system

### ISSUE THREAD

**Issue by Noobyguy775** [NatroTeam/NatroMacro#16]
### What happened?

Roblox changed their private server links to be less complicated and not need the game ID, shortening the link overall. However the macro is designed in a way that disallows links that are not of the old format:
` roblox.com/games/{{ ID }}?privateServerLinkCode={{ ID }}`
Roblox has started rolling out this change yesterday (October 9th), and now regenerating a private server link will result in the following format:|
`roblox.com/share?code={{ ID }}&type=Server`

Links using the old format will still work, however regenerating your private server link will result in the newer format.
You can read more about it [here](https://devforum.roblox.com/t/improved-private-server-links/2628225)

### Steps to reproduce

(Note that this a slow roll-out, it may not be available to every user)
1. Go to any game that you own a private server in
2. Click regenerate link
3. Either the link will be in the old format or the new format (depending on if you have the rollout yet)

Versions 0.6.3-0.9.6 are affected

**Comment by zspz** [comment]
The solution above will be recommended by the Balloon Tooltip if a `/share?code` link is entered.

Roblox's `resolve-link` API requires an authenticated POST request, so it is not possible to resolve these links in the macro. Removing deeplinking because of this is also not appropriate. So, there is pretty much nothing we can do in terms of the macro.

Users will have to get used to the extra step involved in the solution above, instead of directly pasting the server link into the GUI.
