### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by fazzzzlyk** [NatroTeam/NatroMacro#235]
### Have you searched the existing bug reports?

Yes

### What happened?

![image](https://github.com/NatroTeam/NatroMacro/assets/157749070/7bcbaf2d-46ab-43d2-b7d6-c8eae2a77c70)

### Steps to reproduce

1.help
2.please
3.me

### What would you expect to happen?

help

### Natro Macro version

0.9.9.2

### What is your Discord username?

skalimilano1

**Comment by probssplayer** [comment]
most likley not right size in ur settings

**Comment by ZackAttack4987** [comment]
I find it works anyway, and if it doesn't then you should just make sure the display settings are at 100% instead of the usual 300%, and you have to reopen Roblox, so it adjusts for the new change, and you lastly make sure your graphics are at 1 for lowest lag possible. Though I'm not an admin/helper, that's what I do when it tells me that.

**Comment by probssplayer** [comment]
I already know why it happend i had a collor filter on on acedent wich i
dint realise becaus it just looked the same lol


Op vr 26 jan. 2024 02:33 schreef ZackAttack4987 ***@***.***>:

**Comment by misc-et** [comment]
This is due to settings, rather than a bug. Check the guide in our Discord knowledge base, and make a support post there if it doesn't resolve.
