### ISSUE TITLE
Converting Problem

### ISSUE THREAD

**Issue by HoverLois** [NatroTeam/NatroMacro#255]
### Have you searched the existing bug reports?

No

### What happened?

When converting honey, i got into the hole between my hive and the other, then i got resetted with 1 million pollen on my backpack. Please fix this.

### Steps to reproduce

1.
2.
3.
n

### What would you expect to happen?

n

### Natro Macro version

*v0.9.9.2*

### What is your Discord username?

*hover0229*

**Comment by zspz** [comment]
The walk back from field paths in v0.9.9.2 have been extensively tested, so this is likely not to be a bug.
If you updated directly from v0.9.7 or v0.9.8, there may have been issues with importing the new paths, so try redownloading the macro.
Otherwise, check that your MoveSpeed is set correctly in Settings tab.
