### ISSUE TITLE
is it possible to make the macro even more efficient?

### ISSUE THREAD

**Issue by eddieeeeeeeeeee** [NatroTeam/NatroMacro#296]
### Have you searched the existing suggestions?

No

### What is your suggestion?

This macro is the best and all but i see some parts which are wasted time... like how we have to wait 19 secs for bees just to collect a dispenser. we could easily cut off that time since you dont need bees to use a dispenser. same with field boosters, quests and robo/ant passes

### How will this improve Natro Macro?

fairly straightforward... makes it more efficient

### What is your Discord username?

e.d.die

**Comment by eddieeeeeeeeeee** [comment]
additionally i think we could make a few cuts rather than resetting

eg using blue teleporter after collecting blueberry dispenser

another eg :/ straight up running to the next bug kill spot rather than resetting, waiting then going there

yet another eg... stop bug looting after a token link has been detected

these features i think seem fairly easy to make (i may be wrong)

**Comment by Noobyguy775** [comment]
> additionally i think we could make a few cuts rather than resetting
> 
> eg using blue teleporter after collecting blueberry dispenser
> 
> another eg :/ straight up running to the next bug kill spot rather than resetting, waiting then going there
> 
> yet another eg... stop bug looting after a token link has been detected
> 
> these features i think seem fairly easy to make (i may be wrong)

1. Great idea!

2. I'm implementing more [reset -> field -> field] bug runs instead of [reset -> field -> reset -> field], so expect to see more of this in the future

3. The detection already exists, but sadly it's hard to detect the token link text at the bottom due to how the gui elements in the bottom right slowly fade out, so the color is constantly changing. (Although it could be made better)


Also, in the main issue:
- It waits 20 seconds for ant passes to ensure all of your bees are awake if it's going to do an ant challenge
- It waits a variable amount of time for bug runs, so you don't die to the bugs, you can change how long it waits with the hive bees option in the settings tab
- It waits a variable amount of time for harvesting a planter if you're going to pine tree, rose, pumpkin, cactus, or spider, which can also be changed using the hive bees option in the settings tab
