### ISSUE TITLE
Time Set

### ISSUE THREAD

**Issue by Lilbakerstinks** [NatroTeam/NatroMacro#315]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

It could be cool to have the macro have a set time to start and end (ei 15:00 to 00:05). This could be set for certain days, all days, or weekends. AHK does in fact have limits as I understand but ahk is compatible with python which could do this, (I don't know about deprecated only 2). 

### How will this improve Natro Macro?

This could help people not manually/ remotely turn the macro on but have it automated which could be a real big help. Also some people aren't allowed to macro overnight so it could turn off before parents wake up, not trying to encourage said stuff anyways.

### What is your Discord username?

lilbakerstinks (Symbol)

**Comment by Lilbakerstinks** [comment]
I meant to mark yes**

**Comment by zspz** [comment]
I don't see a benefit to having this option within the macro. Apart from using remote control, if people want to schedule this, it can be easily done with e.g. Task Scheduler or a separate script.
The "limits" of AHK are often due to lack of knowledge of the language itself and the language it's compared with. AHK is a very powerful language, and there's a reason it's widely used for automation.
