### ISSUE TITLE
Enter Fullscreen upon Reconnect 

### ISSUE THREAD

**Issue by lechiken** [NatroTeam/NatroMacro#316]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

My suggestion is simple; automatically make the window fullscreen upon reconnect. It likely could be done relatively easily by just making the macro press the fullscreen hotkey (Fn + F11, at least for windows).

### How will this improve Natro Macro?

This could help as it can increase performance for some low end computers (such as myself), but is mostly just a nice quality of life feature.

### What is your Discord username?

lechiken

**Comment by zspz** [comment]
This is not necessary for anyone because Roblox already saves the last window size and the fullscreen option if it's selected through Settings (and not F11).
Also, generally, the macro is designed to work for all resolutions and window sizes apart from those with in-game limitations (e.g. 800x600 has overlapping game UI elements).
