### ISSUE TITLE
automatic drift comp

### ISSUE THREAD

**Issue by eddieeeeeeeeeee** [NatroTeam/NatroMacro#363]
### Have you searched the existing suggestions?

No

### What is your suggestion?

automatically have drift compensate on if we set our sprinkler to supreme saturator

also change path to e_lol/supercat/whatever is optimal with drift comp

and maybe have cloverxsnake cactusxsnake and snaildance in the paths without needing to download from discord

### How will this improve Natro Macro?

pretty self explanatory

### What is your Discord username?

e.d.die

**Comment by zspz** [comment]
- I don't think automatically enabling FDC is a good idea, especially because a lot of paths have internal drift compensation so it's not needed.
- The reason that the default pattern settings are for non-FDC users is that we would get hundreds of support requests about Field Drift, you can easily alter the default settings by saving your desired ones if you have Supreme Sprinkler.
- We cannot add every pattern to the macro by default, because then we would have an endless stack of files in the patterns folder when the user can just download it themselves.
