### ISSUE TITLE
manual planters holding doesnt wait for planter to be full

### ISSUE THREAD

**Issue by Brickster1221** [NatroTeam/NatroMacro#373]
### Have you searched the existing bug reports?

Yes

### What happened?

![Screenshot 2024-03-09 171147](https://github.com/NatroTeam/NatroMacro/assets/28486687/1b51238c-354c-4a63-bf9e-4d51a906e088)

the macro holds it even tho its clearly not finished, even though i have the settings set to harvest at full
plz fix its making me wait till after school to see if my planters puffed, and yes this has happened several times

### Steps to reproduce

1. make macro plant a planter anywhere
2. wait for it to try and harvest it (usually happens when macro is stopped and started again)

### What would you expect to happen?

macro sees that planter is not finished so it sets the harvest time to whatever the percent is instead of holding it immediately

### Natro Macro version

v0.9.9.3

### What is your Discord username?

brickster1221

**Comment by Brickster1221** [comment]
WRONG IMAGE

**Comment by misc-et** [comment]
Thanks for reporting this issue. Planter timer detection has now been implemented in this option for future macro releases.
In the meantime, make sure you set each planter to full instead of time in the planters tab, and if it's occurring mainly when you have left the game for some time and then rejoined, you can update the planter timers using F5 when you rejoin.

**Comment by Noobyguy775** [comment]
Fixed in v1.
