### ISSUE TITLE
Memory match ignoring royal jellies doesn't work

### ISSUE THREAD

**Issue by xdjoee** [NatroTeam/NatroMacro#393]
### Have you searched the existing bug reports?

No

### What happened?

I have turned on ignore royal jellies among other items, and when I watched it do the extreme memory match and the mega memory match it matched royal jellies in both of them

### Steps to reproduce

1. open natro
2. enable memory matches
3. disable royal jellies
4. run the macro

### What would you expect to happen?

not to pick the jellies and to look for other items instead

### Natro Macro version

1

### What is your Discord username?

xd_joe

**Comment by bruor** [comment]
+1,  I've noticed this as well, if it doesn't have any other known matches to uncover at the last step, it will go for jelly instead of trying for another item.  

I've also noticed that sometimes the macro will click on a tile that it has already uncovered, while searching for items, almost like it doesn't realize that it should already know what is under that tile.

**Comment by Noobyguy775** [comment]
merged with #501
