### ISSUE TITLE
Timer display

### ISSUE THREAD

**Issue by seagullius** [NatroTeam/NatroMacro#410]
### Have you searched the existing suggestions?

No

### What is your suggestion?

Add an overlay option that displays desired timers such as respawn timers for bugs, despenser timers, clock etc.

### How will this improve Natro Macro?

means we can stay on top of bugs and dispensers while playing manually without having to set timers ourselves

### What is your Discord username?

@doory_

**Comment by ninjubaer** [comment]
Hello @seagullius 
There is currently such a display in the remote control when you run the command `?timers`.
I dont think we will implement a larger timer window for on the screen so we dont use up too much space because that can cover important regions that are used in the image searches.
I hope that help!

**Comment by Noobyguy775** [comment]
#377
