### ISSUE TITLE
Add a feature that makes it so it doesnt harvest smoking planters (toggleable)

### ISSUE THREAD

**Issue by Wimfish1** [NatroTeam/NatroMacro#416]
### Have you searched the existing suggestions?

No

### What is your suggestion?

So in the planters section there would be a little box saying "Harvest smoking" and you can toggle it on and off to make it so the macro wont harvest your planter if its smoking.

### How will this improve Natro Macro?

I think it'd benefit users as theres plenty of people who like to maintain nectars and macro overnight but also want to do puffshrooms and most runs require smoking planters to enter but the macro always harvests them.

### What is your Discord username?

Wimfish1

**Comment by ninjubaer** [comment]
Hello @Wimfish1 
We are aware that this would be a very nice feature but since the smoke of smoking planters is very hard to detect this feature is really hard or even impossible to implement.
Although there is a option in manual planters that allows you to not harvest until you choose so in the remote control

**Comment by Wimfish1** [comment]
aw ok, thanks for considering it though

**Comment by Noobyguy775** [comment]
added via manual planters, likely to not come soon
