### ISSUE TITLE
taskbar

### ISSUE THREAD

**Issue by bigmonster2710** [NatroTeam/NatroMacro#42]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Like the last version of the natro macro you could pin onto an auto hotkey icon on the taskbar making it easier to access without going into your files and pressing the start file. This feature isn't available anymore because the script is not found on this version. but is found on the previous version. 

### How will this improve Natro Macro?

It would make it bit easier to navigate and start up this program. saving a bit more time, instead of having to go to files and manual having to start it up.

### What is your Discord username?

bigmonster2710

**Comment by Noobyguy775** [comment]
> You already are able to pin it to task bar how it currently is.
Steps:
create a shortcut to start.bat
add cmd.exe in the target
pin to taskbar
shift + right click the shortcut just pinned
remove the cmd.exe from the target

**Comment by zspz** [comment]
This was only coincidentally a feature in the last version, because the executable target was called NATRO_MACRO.exe, matching the filename of the main script natro_macro.ahk.

You can still do this like the method Nooby stated above, just needs an extra step (creating a shortcut manually) because the executable has now been renamed to AutoHotkeyU32.exe (its original name).

However, I would suggest creating a shortcut to the macro directly instead of START.bat, as the CMD icon could be confusing and does not group the newly opened Natro Macro window.

1. In File Explorer, right click -> create new -> shortcut
2. Set 'Target' to `"{natro folder}\submacros\AutoHotkeyU32.exe" "{natro folder}\submacros\natro_macro.ahk"`, replacing `{natro folder}` with the full file path to your downloaded Natro Macro folder
3. Click OK, drag the newly created shortcut to taskbar
4. You can now optionally delete the shortcut in File Explorer
