### ISSUE TITLE
Keyboard does not work after using natro macro for a perioid of time

### ISSUE THREAD

**Issue by Qlrift** [NatroTeam/NatroMacro#450]
### Have you searched the existing bug reports?

Yes

### What happened?

For some odd reason, natro macro does not like it when i macro for a few days and decide to make the keyboard unsuable unless i retstart my pc. Natro pls fix

### Steps to reproduce

1. Unplug keyboard
2. Run natro macro for *god knows how long*
3. Plug keyboard back in
4. Cry about it and restart your pc so it works again

### What would you expect to happen?

The keys on the keyboard will not register thus making you restart the device or continue macroing

### Natro Macro version

1.0.0.1

**Comment by misc-et** [comment]
Thanks for your report. We haven't had other reports of this issue and I haven't been able to replicate it following your steps (although to be fair, I didn't cry about it per Step 4, so perhaps it's because I missed that part), so it seems this may be a specific issue to your set-up rather than a macro bug.
