### ISSUE TITLE
Natro Macro hive slot bug

### ISSUE THREAD

**Issue by faaefafafaf** [NatroTeam/NatroMacro#459]
### Have you searched the existing bug reports?

No

### What happened?

so ye basically when i set slot to 6 its going to take slot no6 but if ill get disconected and my macro will open my private server its taking slot no1. not the slot 6 its set in the settings

### Steps to reproduce

1.turn on macro and set hive slot to 6
2. disconect from the game (wait for a internet lag or turn on wifi for a sec)
3. look what the macro does (it takes different slots)

### What would you expect to happen?

i expect you all there to fix this bug because macro is glitching due to this

### Natro Macro version

1.0.0

### What is your Discord username?

black_4070

**Comment by Noobyguy775** [comment]
Slot 1 is closest to the red cannon.
Slot 6 is closest to the honey dispenser.

When you reconnect, the macro will try and take the slot you set in settings tab. If the slot is taken/not found, it will stop walking left, and turn around the right and claim the first slot it can.

I believe you think that slot 6 is near the red cannon? Or people took slots 6-2, otherwise I don't see a way this could happen, unless you send a video or explain a bit better.

**Comment by faaefafafaf** [comment]
Slot no6 is for me closest to the red cannon and slot no 1 is closest to
the honey dispenser
I'm playing on private server so no one can take slots so the macro should
take slot 6 as I set in setting (the closest to the honey dispenser) but
it's taking slot no1 (the closest to the red cannon) and when I got
disconnected with no one at the server macro rejoined and took slot no 6
(closest to the honey dispenser) i will send u video in the next mail
message so I can prove it works like I said

wt., 14 maj 2024, 07:38 użytkownik Nooby ***@***.***> napisał:

**Comment by Noobyguy775** [comment]
Did you get the video?

**Comment by misc-et** [comment]
Thanks for your report, we aren't able to replicate this issue so will close it, but if you are able to record a video please feel free to post and reopen it.
