### ISSUE TITLE
Natro Macro Simple Reconnect

### ISSUE THREAD

**Issue by B1astcharge** [NatroTeam/NatroMacro#482]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Add an option to where instead of the macro having to do a complicated thing to reconnect when you disconnect it simply presses the reconnect button. This feature would only work for public servers and if there is no reconnect button it will fall back to other methods of reconnecting.

### How will this improve Natro Macro?

Whenever I'm macroing and I disconnect it waste a lot of time trying to load in and recently has been failing to load in. I hope that this will allow for faster load times and an alternative to deeplinking for public servers.

### What is your Discord username?

the_trueepicgoat

**Comment by ninjubaer** [comment]
Hi @B1astcharge 
Last time i checked the `reconnect` button can actually reconnect to servers aswell since the [deeplinks](https://devforum.roblox.com/t/developer-deeplinking-beta/1904069) became a thing. Although this is not something that i believe is worth the extra one or two seconds you get from it and you can never really know if it successfully joined the same server again or not. So this is something that is not planned in the future.
ninju
