### ISSUE TITLE
Auto-Collecting Materials

### ISSUE THREAD

**Issue by DeathBattleBoxing** [NatroTeam/NatroMacro#497]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

This feature will get any material that is needed for craftings.

### How will this improve Natro Macro?

It would be used for crafting things like the Gummy Mask.

### What is your Discord username?

bighead0970

**Comment by misc-et** [comment]
Thanks for this suggestion. The game includes a very broad range of materials to collect and items to craft, and the options to collect each will vary by user game stage and planters owned. The aim of the macro has always been to supplement play rather than play the game for you. 

However this suggested functionality may potentially be achieved slightly differently through suggestion https://github.com/NatroTeam/NatroMacro/issues/77, which allows users to create and share presets for specific task settings .
