### ISSUE TITLE
Auto import settings.ini from previous versions

### ISSUE THREAD

**Issue by Noobyguy775** [NatroTeam/NatroMacro#5]
### Is there an existing suggestion that is already proposing this?

- [x] I have searched the existing suggestions

### What is your suggestion?

so, each time you install a new natro version, you either have to _painstaking redo all your settings_, or if you are experienced you can just drag `settings.ini` into your new install. My idea is that when you install a new version you are prompted by a gui to import your old settings into the new install. It would search in the folder you are running it from, or from common folder locations.

It could search for the 2nd latest version installed
i.e: _you're installing 0.9.6 and you already have 0.9.5 in your downloads_

### How will this improve Natro Macro?

It would save time for everyone, and for the people who don't know about the trick with `settings.ini` it would be amazing.

### What is your Discord username?

noobyguy

**Comment by alaninnovates** [comment]
An alternative is an auto-update feature that automatically fetches for the latest release from github and replaces the current install, but still preserves settings.

**Comment by zspz** [comment]
accidentally edited @Noobyguy775's comment while reading

**Comment by alaninnovates** [comment]
To solve the issue of custom paths being moved over, there could be a path version variable declared in each path, which would increment or change upon a path being updated in the real version. Then, the user could be prompted: "It looks like paths have been updated! Select the paths that you would like to update:", and have all of the paths auto-selected. The user can then deselect the paths that they have made custom.

The issues that I can foresee with this are:
- User doesn't understand what the updator is trying to tell the user, and unselects all of the checkboxes
- User changes the path version by hand within their path file
However, this eliminates the need to store the "old" path and compare them, as that may be tedious to implement.

**Comment by zspz** [comment]
There are a few issues I can think of with a manual version increment in paths, including reading (even if it's only the first line) a very large number of files (each path), and reduced backwards compatibility (for paths made for versions <0.9.7 which don't have any version variable).
Instead, I can just get paths changed between version tags [using GitHub API](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#compare-two-commits). Since the old version of Natro Macro would remain untouched, I'm leaning towards just copying over the user's old 'paths' folder, and force replacing only the changed paths from the new 'paths' folder.

**Comment by zspz** [comment]
thanks for the suggestion! auto-update is ready for v0.9.7 😄 
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/ef236c34-3864-45dd-9201-422d1f0e7be3)
![image](https://github.com/NatroTeam/NatroMacro/assets/142021753/a7d6beb0-3a19-49b6-b567-241356dea238)
