### ISSUE TITLE
Natro Macro taking unusually long time to check spawn

### ISSUE THREAD

**Issue by ThrowawayMoment** [NatroTeam/NatroMacro#515]
### Have you searched the existing bug reports?

No

### What happened?

Normally, Natro Macro will wait ~1.5 seconds before checking the spawn to make sure you spawned at the hive, however my natro macro takes ~10 whole seconds just to check the hive. It wastes a pointless amount of time and I don't know why it started to happen.

### Steps to reproduce

1.Download natro macro
2.Get some magical wizard to break Natro Macro
3.Somehow, it's taking 10 seconds to check the spawn.

### What would you expect to happen?

I would appreciate it if I got some help with fixing this problem without having to reinstall natro, lose my settings, and not even guarantee that it works.

### Natro Macro version

1.0.0.1

**Comment by Noobyguy775** [comment]
The top right of your screen is probably blocked, or you're having misdietection issues. If you still have trouble after this, you can get macro help in our discord https://discord.com/invite/natromacro

It's caused by `nm_Reset()` looking for the empty health bar in the top right of the screen (roblox feature)

**Comment by ThrowawayMoment** [comment]
> It's caused by `nm_Reset()` looking for the empty health bar in the top right of the screen (roblox feature)

No health bar seems to appear when I reset, manually and with the macro.
