### ISSUE TITLE
Panda Bear Quest

### ISSUE THREAD

**Issue by Tlogy1** [NatroTeam/NatroMacro#530]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

You guys should add a auto quest for panda bear and for it to work it turns on all bug runs and all it will do is recieve and turn in quests to panda bear when they are done.

### How will this improve Natro Macro?

It will make it easier for people who don't want to grind panda bears bug quests because of how long the cooldowns for bugs are.

### What is your Discord username?

tlogy

**Comment by misc-et** [comment]
Thanks for this suggestion. Because the macro is designed to assist with some of the repetitive, grindy tasks, rather than replace active play, we wouldn't specifically add in the main quest-lines. If you'd like to use the macro to assist with some of Panda Bear's quest tasks, the best option would be to enable the specific bugs you need for each quest.
