### ISSUE TITLE
Mondo Chick Buff - Return to Hive by "Reset"

### ISSUE THREAD

**Issue by floydmarcuss** [NatroTeam/NatroMacro#534]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

Whenever you have "To Hive By:" set on "Walk" in the Gather tab, when Mondo Chick gather interruption happens, you will _walk_ back to your hive to kill Mondo Chick eventually. This feature will add an option to change Mondo Chick Buff's interruption-specific return to hive option for Mondo Chick while inside a field—not because your "To Hive By:" Gather setting is set to "Walk." These options would be "Reset" and "Walk."

### How will this improve Natro Macro?

This will save time (around 40 seconds for returning from Pine Tree Field specifically) returning to hive—especially for fields further away, because eventually the macro will reset anyways for the Mondo Chick Buff once the timer ends (making the bag you saved by walking to hive irrelevant).

### What is your Discord username?

m.arcuss

**Comment by DullSmallmega176** [comment]
technically it's faster returning to field by walk instead of resetting, i have modified paths that can return back to hive in 15-30 seconds depending on your haste

**Comment by misc-et** [comment]
Thanks for your suggestion. It seems like the main issue here is losing the backpack pollen. 

As Dully mentioned, resetting is not typically much faster than walking because of the time bees take to awake. 

I think an alternative solution is to have an option to back to hive (instead of resetting) and converting after mondo, preserving the backpack pollen.

**Comment by misc-et** [comment]
Closing as overlaps with https://github.com/NatroTeam/NatroMacro/issues/545
