### ISSUE TITLE
Replace feature

### ISSUE THREAD

**Issue by GoshaTsv** [NatroTeam/NatroMacro#54]
### Have you searched the existing suggestions?

No

### What is your suggestion?

If you get an amulet, natro macro will automatically replace it. It will work with king beetle or stump snail Incase someone was farming it overnight

### How will this improve Natro Macro?

Incase of a crash, the amulet would go to waste. That would help very much if the user got the first amulet.

**Comment by zspz** [comment]
The only reason this has not yet been considered is because we will undoubtedly have people turn this on by accident and then blame Natro Macro for replacing their amulets.
Amulets can already be pinged for, screenshotted, and sent to Discord. Remote control allows you to replace it while the macro is running. The macro runs with almost full functionality when an amulet prompt is on screen.
Therefore, we are not considering this feature for now.
