### ISSUE TITLE
auto Promo Code Redeemer

### ISSUE THREAD

**Issue by R0ckLOL** [NatroTeam/NatroMacro#549]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

A button you could press in the Misc Tab that opens the settings tab inside of BSS and put in a bunch of old and new codes
it would work like if you were to press the Export Hive Bee List button.

### How will this improve Natro Macro?

it would improve natro macro users by using the benefits of the codes buff for overnight afking so Users don't have to search the internet to see if there are new codes.

### What is your Discord username?

tartarus._.

**Comment by misc-et** [comment]
Thanks for your suggestion. It's an interesting idea, but we'd be unlikely to add this to the macro for a couple of reasons - the dependencies on external data sources, and that most users would be likely to prefer to control when and how they use each code for maximum gain, rather than having them used indiscriminately by the macro.
