### ISSUE TITLE
Convert Pollen In A Fast and Safer Way Where You Won't Lose Your Grinded Pollen

### ISSUE THREAD

**Issue by MohamadAlawedat** [NatroTeam/NatroMacro#550]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I was just disconnected from Bee Swarm Sim server due to "lost connection" that keeps constantly happening, and I realized that the macro keeps failing to walk back to the hive, multiple times, Maybe because of the settings I'm using( the default settings < when you pick a field, each one has its own settings>). it keeps resetting and the pollen that the macro spent grinding gets reset.

I keep getting "Lost Connection" multiple times. This time it happened again and I realized something! Notice: when Natro Macro reconnects you and goes to "Claim" a hive?

I realized you could just turn off the internet connection and turn it on again to reconnect to the server and convert Pollen.

### How will this improve Natro Macro?

If it's done well you can guarantee your grinded pollen won't go to waste along with the time it took to collect it!!!

By making the macro turn off the internet when it's time to convert, pollen is guaranteed to convert to honey. Also when it's trying to get stuff from the dispensers, it wastes a lot of time and you barely get anything, so if it's possible to add it as an option for us to use it will be helpful. 

Why haven't guys done it yet, no way you haven't thought of this idea.

### What is your Discord username?

KillerFrust#2226

**Comment by misc-et** [comment]
Thanks for your suggestions. If I understand correctly, you are suggesting that the macro should disconnect your PC from the internet when it can't return successfully to hive, so that it can rejoin the game and convert your bag? 

In general, we wouldn't add features to the macro that would change general computer settings in this way. It's likely that your issue is related to incorrect movement settings (not field settings), so check our [discord server](https://discord.gg/natromacro) Knowledge Base for details on how to fix this or raise a help ticket there for support.

Regarding the dispensers, these are an option that you can enable/disable in the Collect/Kill tab.

**Comment by MohamadAlawedat** [comment]
> Thanks for your suggestions. If I understand correctly, you are suggesting that the macro should disconnect your PC from the internet when it can't return successfully to hive, so that it can rejoin the game and convert your bag?
> 
> In general, we wouldn't add features to the macro that would change general computer settings in this way. It's likely that your issue is related to incorrect movement settings (not field settings), so check our [discord server](https://discord.gg/natromacro) Knowledge Base for details on how to fix this or raise a help ticket there for support.
> 
> Regarding the dispensers, these are an option that you can enable/disable in the Collect/Kill tab.

No more like close the window and reconnect using "Deeply" I think it's called. and it will go the hive anyways.
I mean surely closing the window is no big deal, right! you wouldn't change the windows settings!
