### ISSUE TITLE
Automatically evaluate amulets

### ISSUE THREAD

**Issue by GummyPikmin** [NatroTeam/NatroMacro#57]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

So I thought of this idea when I was about to turn King Beetle macroing on when I realized, “why isn’t there an ability to macro for amulet passives, i.e.: macro KB over and over until he drops an amulet with ideal passives I want?” For example, what if you wanted a Beetle Amulet with 100% Convert Rate, +1 Bee Attack, and 100% Mushroom and Strawberry Pollen? You could like check them off in a menu and you could check off ones you aren’t particularly picky about (ex: a 3/4 or something). Just a way to macro King Beetle amulets, and maybe find a way to be able to macro the others, though Cog and Ant might be tricky to be able to macro, but it would still be cool. Even at the very least macroing King Beetle and/or Moon, and maybe Star Amulets would be cool.

So, in more detail, if you wanted a Beetle Amulet with 100% Convert Rate and +1 Bee Attack, but aren’t picky about 100% Mushroom and Strawberry Pollen, you could select convert rate and attack in a column called like “Preferred buffs” or something and check off the other in one called “Optional buffs.” You could also select “Max Amulet Buffs” and takes both columns into consideration. You could also have the same deal with other amulets if you were to incorporate those, like for example Cog (if you somehow were to add that, color me impressed), if you are aiming for Gold or Diamond for Glitched Drives or Digital Bee respectively, you could check that off so you have that secured for later use, regardless of buffs. The list of features could go on and on but that’s the bare minimum.

### How will this improve Natro Macro?

Amulets are very important, even outside macroing, and so I think this will be a monumental addition to macroing, so us players don’t have to worry about getting the amulets ourselves. Even if we wouldn’t be able to gather, kill, etc while getting amulets, just let the player know that. I think macroing amulets would be a good addition, even though macroing for them defeats the purpose of getting good ones, but macroing in general defeats the purpose of playing the game, so I digress.

### What is your Discord username?

gummypikminproductions

**Comment by zspz** [comment]
- Ant Amulets are not separately configurable (i.e. keep amulet on screen / do nothing option) in Natro Macro and it probably won't be in the near future because the amulet's quality scales with score, and any macro at the moment will not perform better than a human.
- Cog Amulets (i.e. RBC) is very much possible to macro, but it will have the same reasoning as Ant Amulets in that a human will perform much better than a macro, so there is very little point to adding a dedicated Amulet option to the macro's version.
- That leaves King Beetle Amulets and Shell Amulets. These can already be pinged for, screenshotted, and sent to Discord. Remote control allows you to replace them while the macro is running. It would provide little benefit relative to the effort (and option complexity) required to implement automatic amulet analysis, so we are not considering this for now. However, it can be considered in the future so I will leave this issue open.

**Comment by misc-et** [comment]
In addition to sp's comments, it is felt that this may be a high-risk option. Closing for now, but it can be reopened if someone wishes to work on it or we have further requests.
