### ISSUE TITLE
Field Shift

### ISSUE THREAD

**Issue by Mrelephant120** [NatroTeam/NatroMacro#573]
### Have you searched the existing suggestions?

No

### What is your suggestion?

I am suggesting that we don’t only have a drift comp for people with supreme saturator because some people have other sprinklers like silver. So I am suggesting that there be a drift comp for all sprinklers. You could maybe do it by the player putting down to sprinklers and then the macro detects those 2 sprinklers and therefore keeps the player in between the sprinklers and not let them go out. So then there could be an imaginary vertical line through the sprinklers and that is the boundary for the player/ macro and the macro can’t force the player outside those lines

### How will this improve Natro Macro?

This will improve Natro Macro because many people don’t have a supreme saturator and might only have the basic to diamond sprinkler and then people can hunt for stickers with natro macro because many get stickers by macroing

### What is your Discord username?

Mrelephant120

**Comment by Noobyguy775** [comment]
the way you suggested doing it is functionally impossible

field drift is caused by lag/inefficiencies affecting both roblox and rarely the script as well
the reason FDC is only available to users with supreme saturator is that the neon blue pixels are only rarely found in other things in the game, compared to the common colours of the other sprinklers
