### ISSUE TITLE
other ways of field compensations

### ISSUE THREAD

**Issue by borr4r44** [NatroTeam/NatroMacro#625]
### Have you searched the existing bug reports?

No

### What happened?

im early mid game and still not have ss i hope you can help me or add another way of field drift compensation in pepper*

### Steps to reproduce

1.farm in pepper 
2.
3.

### What would you expect to happen?

another way of field drift compensation

### Natro Macro version

1.0.0.2

### What is your Discord username?

yang1i

**Comment by peacocksir** [comment]
Unfortunately we have basically no way of actually implementing this, the reason we can do it with the supreme saturator is because it has a different texture than anything in the game, so you are easily able to decipher it from other things. It would also be hard to add it and take time to test and optimize. Not really something we are focused on as well because the majority of the macro users have it. If we have nothing else to add later down the line I might consider adding/figuring out a way to add it but it will not be happening soon.
