### ISSUE TITLE
Nature Macro Mac book

### ISSUE THREAD

**Issue by Cars4L** [NatroTeam/NatroMacro#643]
### Have you searched the existing bug reports?

Yes

### What happened?

I would like to know if this works for Mac book. I tried it a couple of times and it hasn't worked.

### Steps to reproduce

1. I tried
2. Didn't 
3. Work

### What would you expect to happen?

I expected it to work

### Natro Macro version

newest version

### What is your Discord username?

carlife4

**Comment by Cars4L** [comment]
Natro not nature

**Comment by Therogamer** [comment]
Natro does not work on macOs, due to AutoHotKey being built for Windows only (using DllCalls, etc.). An alternative is Existance, macro made for macs, and only for MacOs. You can find information and the download in their discord. https://discord.gg/D88ZJrcQbm
- Taken from Natro Macro's discord server
