### ISSUE TITLE
Questgivers quest not being read properly or being ignored

### ISSUE THREAD

**Issue by dreadmp3** [NatroTeam/NatroMacro#724]
### Have you searched the existing bug reports?

No

### What happened?

This affects: brown bear, black bear and polar bear.
If you're supposedly already redeemed a quest from the bears, you would encounter when the macro ignores the quest, or ignores it completely and tries to get a new quest from the bear.

### Steps to reproduce

1. Set the 3 bears mentioned in the issue to do their quest
2. Claim a quest before macroing
3. The macro tries to find it but it won't (may only read some quests, but it gets stuck for sure in leisurely lowlands, coco-pepp-clove-pine and high protein bug bar.(currently the quests my macro was stuck on))

### What would you expect to happen?

The macro keeps on going to the questgiver and try to get a new quest while you have one already. In worse cases, it flags the quest as a different one. (ex. leisurely lowlands being triple trek)

### Natro Macro version

1.0.0.2

### What is your Discord username?

dread.mp3

**Comment by DullSmallmega176** [comment]
This is already being worked on, you have some of it almost correct but you forgot to include Riley bee.

Currently the "fixed" quests are almost all of them on polar and black.
this includes quest name and the Questgiver's name on the quest title

the only difference for brown bear is the questgiver name. just needs a bit more until it works but a pain to test since the pollen requirement is just horrible

but Riley bee is special and can't really detect that the quest is completed. i forgot which one but it is there

**Comment by misc-et** [comment]
https://github.com/NatroTeam/NatroMacro/issues/669
