### ISSUE TITLE
The destruction of a mid game player

### ISSUE THREAD

**Issue by Bigi123438** [NatroTeam/NatroMacro#756]
### Have you searched the existing bug reports?

Yes

### What happened?

The macro used 130 of my glue, 70 tropical drinks, 40 enzymes, and around 80 oils. It also spent 30billion honey on royal jellies and used them on my gifted precise bee. I took a GOOD look at my settings to see if i changed something by mistake, but the settings were the same. I also had 25 less star jellies and also 900 less tickets. Please tell me if i did something wrong or what the hell is wrong with your system, cuz 30 billion is A LOT for me and that gifted precise bee wasn't easy to get!

### Steps to reproduce

1. I left the macro overnight to farm in the pine tree forest
2. It was set to collect the wealth clock, the feast, the samovar, the blueberry, coconut and strawberry dispenser.
3. In the morning, i woke up to 30 billion less honey, a lost gifted precise bee, 15 purple potions, 25 star jellies, 130 glues, 70 tropical drinks, 80 oils and 50 enzymes

### What would you expect to happen?

GIVE ME BACK MY GIFTED PRECISE BEEEEEEEEEE
i also want my 30 billion honey back 
and the star jellies
and the glues

### Natro Macro version

v1.0.0.2

### What is your Discord username?

Биги

**Comment by Noobyguy775** [comment]
First thing to check is your hotbar slots, since the macro presses those without checking what is in them. Currently, your sprinkler is also assumed to be in slot 1

Regarding the precise bee, it is **extremely** unlikely that the macro did that. Someone else probably logged onto your account or used your computer, or something else.

There are thousands of people who have used the macro without it changing their hive slots, I highly doubt this is a new issue.
