### ISSUE TITLE
Roblox had a update

### ISSUE THREAD

**Issue by sUperJaster** [NatroTeam/NatroMacro#788]
### Have you searched the existing bug reports?

Yes

### What happened?

Natro Macro wouldnt work and its from the new roblox ui since it worked before and there was 2 other people talking about it and the effect is it has a warning before it starts and it also takes a while to start moving and walks past the cannon. But if you fix this then Thanks!

### Steps to reproduce

1.
2.
3.

### What would you expect to happen?

Adapting the macro to both ui versions or just the new ui

### Natro Macro version

v1.0.0.2

**Comment by misc-et** [comment]
Can you provide some more detail on what the warning is, and a screenshot?
If it relates to the delay after resetting at hive and before moving, this is a known issue due to the UI update that will be fixed in a future release. Please see our [Discord server](https://discord.com/invite/natromacro) for support.

**Comment by misc-et** [comment]
Closing this post due to inactivity
