### ISSUE TITLE
deleting stickers 

### ISSUE THREAD

**Issue by supsboi101** [NatroTeam/NatroMacro#792]
### Have you searched the existing suggestions?

Yes

### What is your suggestion?

when donating stickers to the sticker printer there should be a setting for auto deleting stickers you don't want, Meaning when you donate a egg and get a sticker you have selected you dont want the macro will delete it for you

### How will this improve Natro Macro?

this will stop you sticker inbox from overflowing and forcing you to manually delete hundreds of stickers you don't want, for example i could donate thousands of basic eggs and only get the 0.1% drops

### What is your Discord username?

primlocksups

**Comment by misc-et** [comment]
Thanks for your suggestion. In the past, we haven't wanted to do this in case of error, so that there isn't risk of valuable stickers being accidentally deleted due to e.g., different user graphic settings. Appreciate that it's a pain to manually delete them, though! 

We did have a different suggestion, to screenshot and send via webhook the inventory and inbox so users can see what's there and when it's full, so perhaps this may be somewhat helpful https://github.com/NatroTeam/NatroMacro/issues/655

**Comment by misc-et** [comment]
Thanks for your suggestion. In the past, we haven't wanted to do this in case of error, so that there isn't risk of valuable stickers being accidentally deleted due to e.g., different user graphic settings. Appreciate that it's a pain to manually delete them, though! 

We did have a different suggestion, to screenshot and send via webhook the inventory and inbox so users can see what's there and when it's full, so perhaps this may be somewhat helpful https://github.com/NatroTeam/NatroMacro/issues/655

**Comment by supsboi101** [comment]
thank you for viewing my suggestion, could also have a disclaimer in bold
that any stickers deleted you are not responsible for
