### ISSUE TITLE
Bug: Meu macro ta bugado pq quando boto pra farm ele farm mas quando a opção Drift Comp ativada ele n detecta meu Sup Saturator e ele fica resetando dunada e fica trocando de servidor mesmo com as opções desligadas

### ISSUE THREAD

**Issue by BielCristian** [NatroTeam/NatroMacro#794]
### Have you searched the existing bug reports?

No

### What happened?

Macro Bug

### Steps to reproduce

1.macro ta bugado pq quando boto pra farm ele farm mas quando a opção Drift Comp ativada ele n detecta meu Sup Saturator
2. e ele fica resetando dunada e fica trocando de servidor mesmo com as opções desligadas

### What would you expect to happen?

farmar sem resetar dunada e Voltar pro Sup Saturator quando sai da field

### Natro Macro version

1.0.0.2

### What is your Discord username?

𝔸𝕩𝟟_𝕊𝕜𝕪𝕝𝕚𝕟𝕖

**Comment by misc-et** [comment]
Thanks for your report. This is likely to be an issue with settings, rather than a bug. Try changing your avatar to a standard size, if it's non-standard right now. Otherwise, please see our [Discord server](https://discord.com/invite/natromacro) for support. 

Note we do also have a Portuguese support channel there.
