### ISSUE TITLE
Spirit Bear Quest's

### ISSUE THREAD

**Issue by 7319Adam** [NatroTeam/NatroMacro#807]
### Have you searched the existing suggestions?

No

### What is your suggestion?

add spirit bear quest's so that you can get more item's like the petal wand the windy bee and the petal belt.

### How will this improve Natro Macro?

for people who are new to bee zone lvl 35

### What is your Discord username?

seekchan

**Comment by misc-et** [comment]
Thanks for your suggestion. We don't plan to add the mainline quests (e.g., Spirit Bear), because the aim of the macro is to help with some of the more grindy repetitive tasks rather than play the main game for you. Some of the quest tasks for Spirit Bear would also be more difficult to macro efficiently.
